code/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :events, only: [ :index, :show ] do
    resources :artists, only: [ :index, :show ]
  end

  get "/map", to: "pages#map", as: :pages_map
end

code/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

code/app/models/artist.rb
class Artist < ApplicationRecord
  #has_and_belongs_to_many :works
  has_many :works, dependent: :destroy
  has_many :events, through: :works
end

code/app/models/artist_from_work.rb
class ArtistFromWork < ApplicationRecord
  belongs_to :work
  belongs_to :artist
end

code/app/models/event.rb
class Event < ApplicationRecord
  #has_and_belongs_to_many :works
  has_many :works, dependent: :destroy
  has_many :artists, through: :works
end

code/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

code/app/models/work.rb
class Work < ApplicationRecord
  belongs_to :artist
  belongs_to :event
  #has_and_belongs_to_many :events
  #has_and_belongs_to_many :artists
end

code/app/models/work_from_event.rb
class WorkFromEvent < ApplicationRecord
  belongs_to :event
  belongs_to :work
end

code/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

code/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_artist, only: [ :show ]
  before_action :set_event, only: [ :show, :index ]
  
  def index
    @artists = @event.artists
    #@artists = Artist.joins(:event).where(event: @event)
    #Artist.joins(:works).where(event: @event)
    #@artists = Artist.joins(:work).where(event: @event)
    #Artist.joins(:event).where(events: @event)
    #Artist.where(event: @event)
    #Artist.joins(:event).where('events.id = ?', params[:query])
  end
  
  def show
    @work = @event.works
  end
    
  private
  
  def set_artist
    @artist = Artist.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

end

code/app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_event, only: [:show ]

  def index
    @events = Event.all
  end

  def show
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

end

code/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :map ]

  def home
  end

  def map
  end
end

code/app/helpers/application_helper.rb
module ApplicationHelper
end

code/app/views/artists/index.html.erb
<div id="artists">
  <h1>Artistas</h1>
  <%= link_to "Voltar", events_path%>
  <h3><%= @event.edition %></h3>
  <ul>
    <% @artists.each do |artist| %>
      <li>
        <span> <a href="artists/1"> <%= artist.name %> </a> </span>
        <span><%= artist.nationality %></span>
        <span><%= artist.delegation %></span>
      </li>
    <% end %>
  </ul>
</div>

code/app/views/artists/show.html.erb
<div id="ShowArtists">
  <%= link_to "Voltar", event_artists_path %>

  <h3><%= @artist.name %> na <%= @event.edition %></h3>

  <p><%= @artist.nationality %></p>
  
  <p>Lista de obras na edição</p>
    <ul>
      <% @work.each do |work| %>
      <li>
        <span><%= work.title %> |</span>
        <span><%= work.date %> |</span>
        <span><%= work.size %> |</span>
        <span><%= work.support %> |</span>
        <span><%= work.technique %></span>
        <% end %>
      </li>
    </ul>

    <a href="/map"> CIRCULAÇÃO </a>
  
</div>

code/app/views/events/index.html.erb
<div id="events">
  <h1>Eventos</h1>
  <a href="/"> Voltar </a>
  <main>
    <% @events.each do |event| %>
      <div id="listEvents" class="listEvents">
          <div><%= link_to event.edition, event_path(event) %></div>
          <span>-</span>
          <div><%= event.place %></div>
          <div><%= event.inicial_date %></div>
          <div><%= event.final_date %></div>
      </div>
    <% end %>
  </main>
</div>

code/app/views/events/show.html.erb
<div id="showEvents">
	<%= link_to "Voltar", events_path%>

	<h2><%= @event.edition %></h2>

	<main>
		<h3>729 artistas </h3>
		<h3>1.854 obras </h3>
		<h3>Distribuição por gênero: </h3>
		<img src="https://media.discordapp.net/attachments/768553883265531957/781997706771693648/hackaton_mulheres_e_homens_brasil_por_sexo_I_Bienal_de_SP_1.png?width=791&height=475" class="figure-img img-fluid rounded" alt="gráfico por gênero">

		<h3>Distribuição por raça: </h3>
		<i>Em etapa de consolidação.</i>

		<h3>25 delegações</h3>
		<ul>
			<li>Argentina</li>
			<li>Bélgica</li>
			<li><%= link_to "Brasil", event_artists_path(@event) %></li>
			<li>Bolívia</li>
			<li>Canadá</li>
			<li>Chile</li>
			<li>Cuba</li>
			<li>Estados Unidos</li>
			<li>França</li>
			<li>Haiti</li>
			<li>Holanda</li>
			<li>Itália</li>
			<li>Japão</li>
			<li>Suíça</li>
			<li>Reino Unido</li>
			<li>Uruguai</li>
		</ul>
	</main>

</div>

code/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CONV.ART</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
     integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
     crossorigin=""/>

    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
     integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
     crossorigin=""></script>

  </head>

  <body>
    <div class="container" >
        <%= yield %>
    </div>
  </body>
  
</html>

code/app/views/pages/home.html.erb
<div id="home" >

  <main class="wrapper" >  
    
    <header>
      <nav>
        <a href="#home">Home</a>
        <a href="#about">Sobre</a>
        <a href="#contactUs">Contato</a>
      </nav>
      <img src="<%= asset_path( 'logo.png' ) %>" />
      <nav>
        <img src="https://www.flaticon.com/svg/static/icons/svg/1617/1617440.svg" />
        <img src="https://image.flaticon.com/icons/png/512/23/23931.png" />
        <img src="https://image.flaticon.com/icons/png/512/25/25231.png" />
      </nav>
    </header>

    <nav>
      <a href="map"> Bienais </a>
      <a href=""> Exposições </a>
      <a href=""> Salões </a>
      <a href="events"> Eventos </a>
      <a href=""> Feiras </a>
    </nav>

    <div class="buttonsOutSide" >
      <a href=""> Quero convergir </a>
      <a href="#about" id="moveDowm" > <img src="https://img.flaticon.com/icons/png/512/25/25623.png"/> </a>
      <a href="#login"> Quero conversar </a>
    </div>
  </main>

</div>

<!-- other section with 100vh -->
<div id="about">
  <h1>Sobre</h1>
  <p>Com o crescente interesse em pensar a arte como fenômeno global , torna se urgente encontrar um meio de articular e analisar comparativamente as informações que as bienais vêm gerando ao longo de sua história.
Instituições como as bienais de São Paulo, Veneza, Dakar, Istambul e tantas outras, mantêm arquivos sobre suas atividades, mas com modos diversos de sistematizar e disponibilizar dados, impedindo sua articulação dinâmica e visualização de padrões e singularidades
Isso impossibilita a compreensão de processos culturais abrangentes e de suas transformações.
A plataforma CONV.ART é um ambiente interativo e colaborativo de convergência para bancos de dados institucionais sobre exposições.</p>
  <div class="authors">
    
    <div>
      <img src="<%= asset_path( 'JO_bolinha.jpg' ) %>" />
      <h5>Designer UI/UX</h5>
    </div>

    <div>
      <img src="<%= asset_path( 'PL_bolinha.jpg' ) %>" />
      <h5>Desenvolvedor Front-End</h5>
    </div>

    <div>
      <img src="<%= asset_path( 'GIU_bolinha.jpg' ) %>" />
      <h5>Desenvolvedora Full-Stack</h5>
    </div>

    <div>
      <img src="<%= asset_path( 'MA_bolinha.jpg' ) %>" />
      <h5>Conceituação e Pesquisa</h5>
    </div>

    <div>
      <img src="<%= asset_path( 'TA_bolinha.jpg' ) %>" />
      <h5>Conceituação e Pesquisa</h5>
    </div>

    <div>
      <i class="fa fa-instagram" aria-hidden="true"></i>
    </div>
  </div>

</div>

<!-- other section with 100vh -->
<div id="login">
  <div class="header">
    <img src="<%= asset_path( 'logo.png' ) %>" />
    <a href="/">Login</a>
  </div>
  <form action="/">
    <h1>Cadastro</h1>
    <div class="inputBlock">
      <label for="fullName">Nome Completo</label>
      <input placeholder="Reginaldo da Cruz" type="text" name="fullName" id="fullName" />
    </div>

    <div class="inputBlock">
      <label for="email">Email</label>
      <input placeholder="email@dominio.com" type="email" name="email" id="email" />
    </div>

    <div class="inputBlock">
      <label for="pass">Senha</label>
      <input placeholder="**********" type="password" name="pass" id="pass" />
    </div>

    <button>Começar</button>
  </form>
</div>

code/app/views/pages/map.html.erb
<div id="bienais" >

  <h1>Bienais</h1>
  <a href="/"> Voltar para a página inicial </a>
  <div id="map"></div>


  <!-- <script type="text/javascript" src="../js/listBienaisOfMap.js" ></script> -->
  <%= javascript_pack_tag 'listMap', 'data-turbolinks-track': 'reload', defer: true %>

</div>